name: 64-linux-host
run-name: Linux x64 binary build
on: [push]
permissions:
    contents: write
    issues: write
    pull-requests: write
jobs:
    config-meson:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-python@v6
            - uses: BSFishy/meson-build@v1.0.3
              with:
                action: build
                directory: gh-build
                options: -w phonycycle=warn
                meson-version: 1.9.1
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
                VER: meson introspect meson.build --projectinfo | jq -r '.version'
            - run: gh release create $VER ./gh-build/typedraw --notes "Created by GitHub Actions."
